---

- name: Add MariaDB repo key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0xcbcb082a1bb943db
  when: engine | lower == "mariadb"

- name: Add MariaDB repository to sources
  apt_repository: repo='deb http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu trusty main'
  when: engine | lower == "mariadb"

- name: Install Python MySQL library
  apt: name=python-mysqldb update_cache=yes

- name: install mariadb-server 
  apt: name=mariadb-server
  when: engine | lower == "mariadb"

- name: install MySQL-server 
  apt: name=mysql-server
  when: engine | lower == "mysql"

- set_fact:
    mysql_root_password: "{{ mysql_root_password }}"

- service: name=mysql state=started

- name: update mysql root password for all root accounts
  mysql_user: 'name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT'
  with_items:  
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: remove the MySQL test database
  mysql_db:
    db=test
    state=absent
