---

# All of the settings in this file are covered by defaults
# so this can be completely empty (or even deleted) and the
# playbooks will still run. There should be no need to edit
# the inividual playbook roles.

synced_folder: /vagrant_synced


############################################################
#                          Apache                          #
############################################################

# Vagrant's working folder will be synced as /vagrant/ but 
# the working directory will be shared in via sshfs to the
# location specified here.
# Additionally, this can be used to link the web files to a
# different path. An example might be a shared hosting web 
# directory like /home/user/public_html or 
# /home/user/webapps/domain.
# If the path is /var/www, the setting will be ignored.
# (and SSHFS mounts will cause all sorts of problems)
vhost_document_root: "{{ synced_folder }}/{{ ansible_hostname }}"

# This is the public_html directory containing the publicly
# visible web files. Yeoman uses app, Laravel uses public,
# Symfony uses web. Sheesh. 
public_web_dir: public


############################################################
#                           PHP                            #
############################################################

# Install PHP debugging tools Xdebug and XHProf
php_debug: true

# THe PHP error_reporting level to be set in php.ini. Error 
# levels can be selectively added or removed, for example:
# 'E_ALL & ~E_STRICT & ~E_DEPRECATED'
# This setting has no effect if php_debug is false. 
php_error_reporting: E_ALL

# If true, run PHP as FastCGI instead of an Apache Module
php_fastcgi: false

# Default timezone for php.ini
# http://www.php.net/manual/en/timezones.php
php_timezone: America/New_York

# Install Composer
install_composer: true

# Path where XHProf will store it's run reports
xhprof_output_dir: /var/tmp/xhprof


############################################################
#                     MariaDB (MySQL)                      #
############################################################

# Enable the MySQL role. This will install MySQL but won't
# remove it if the config is changed
install_mysql: no

# Name of the MySQL database
mysql_db_name: vagrant

# Default MySQL user credentials
mysql_username: vagrant
mysql_password: vagrant

# MySQL root password. (instead of blank)
mysql_root_password: password

# Use older, more compatible MariaDB version. If True, then
# MariaDB 5.5 will be installed. The default is to use the 
# most cutting edge release (v10)
max_mysql_compatibility: false

# Location of MySQL dumpfiles to load into the database.
# Existing data is backed up each time the playbook runs.
mysql_dumpfiles:
  - db/vagrant.sql


############################################################
#                          Avahi                           #
############################################################

# The name which will be advertised over Bonjour/Zeroconf
# '%h' is an Avahi placeholder for hostname
avahi_banner: "%h (Vagrant)"


############################################################
#                         Node.js                          #
############################################################

# The version of node.js to install. (including 'v' prefix)
# The string 'latest' will install the most recent stable 
# version found here: http://nodejs.org/dist/latest/
node_version: latest

# Location of the package.json file to install with NPM. Can
# be an absolute path or relative to the Vagrantfile. If no 
# file is specified or the file doesn't exist, the task will
# be skipped. 
package_json_file: package.json

# Location of a Gruntfile.js. If it exists, try running 
# grunt watch in the background.
gruntfile: Gruntfile.js

# SSH alias for Vagrant's host machine. This is used in the 
# ssh config file and the sshfs mount command
host_alias: vagrant-host

# The username to connect to the host. Defaults to the
# current username. Should have an account and be able to
# log in remotely to the host machine. 
host_username: "{{ lookup('pipe', 'whoami') }}"

# Location where the host-access rsa keys will be created. 
# Public keys will use this file path with '.pub' appended.
ssh_key_file: /home/vagrant/.ssh/vagrant_rsa