---

- command: mktemp ~/.ssh/github_deploy_key-XXXX
  register: github_deploy_key

- name: Copy private key to remote machine
  copy:
    src={{ git_private_key }}
    dest={{ github_deploy_key.stdout }}

- command: mktemp ~/.ansible/tmp/config_fragment-XXXX
  register: config_fragment

- name: Write ssh config fragment
  template: src=ssh_config.j2 dest={{ config_fragment.stdout }}

- shell: cat {{ config_fragment.stdout }} >> ~/.ssh/config

- name: Clone Private Repository
  git:
    repo={{ git_repo }}
    dest={{ site_root }}
    accept_hostkey=yes
