---

- name: install Apache
  apt: name={{ item }} state=installed update_cache=yes
  with_items: 
    - apache2

- name: Make Apache2 not suck
  command: a2enmod {{ item }}
  with_items:
    - rewrite
    - expires
  notify:
    - restart apache

- name: Install apache crontab
  copy: src=apache.cron dest=/etc/cron.d/apache owner=root mode=0644
