---
- name: Make sure the database exists
  mysql_db: name={{ mysql_db_name }} state=present

- name: Create database backup temp directory
  command: mktemp -d /tmp/db_backup-XXXX
  register: db_backup_temp

- name: Backup any existing data
  mysql_db:
    name={{ mysql_db_name }}
    state=dump
    target={{ db_backup_temp.stdout }}/{{ mysql_db_name }}_backup.sql
    login_user={{ mysql_username }}
    login_password={{ mysql_password }}

- file: path={{ vhost_document_root }}/db/backups state=directory
- name: Move database backup to database directory
  assemble: 
    src={{ db_backup_temp.stdout }}
    dest={{ vhost_document_root }}/db/backups/{{ mysql_db_name}}.sql
    backup=yes

- name: Remove the database backup temp directory
  file: path={{ db_backup_temp.stdout }} state=absent

