---
# Create the database first, otherwise the import step will fail
- name: Create the database
  mysql_db: name={{ mysql_db_name }} state=present

- name: Check for dumpfiles
  stat: path={{ vhost_document_root }}/{{ item }}
  register: mysql_dumpfiles_stat
  with_items: mysql_dumpfiles

- name: Populate database from checked dumpfiles
  mysql_db: 
    name={{ mysql_db_name }}
    state=import
    'target={{ item.invocation.module_args[5:] }}'
    login_user={{ mysql_username }}
    login_password={{ mysql_password }}
  when: item.stat.exists
  with_items: 
    - "{{ mysql_dumpfiles_stat.results }}"
