---     

- name: add maridadb apt repo key  #Appears to be idempotent (returns "imported"/"not changed")
  command: sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db

- name: Add MariaDB 10.0 repository to sources
  apt_repository: repo='deb http://ftp.osuosl.org/pub/mariadb/repo/10.0/ubuntu precise main'
  when: not max_mysql_compatibility

- name: Add MariaDB 5.5 repository to sources
  apt_repository: repo='deb http://ftp.osuosl.org/pub/mariadb/repo/5.5/ubuntu precise main'
  when: max_mysql_compatibility

- name: install mariadb-server 
  apt: name={{ item }} state=installed update_cache=yes
  when: not max_mysql_compatibility
  with_items: 
    - mariadb-server
    - python-mysqldb

- name: Install mariadb-server 5.5 (with explicit versions)
  apt: name={{ item }} state=installed update_cache=yes force=yes
  when: max_mysql_compatibility
  with_items:
    - libmysqlclient18=5.5.33a+maria-1~precise
    - mysql-common=5.5.33a+maria-1~precise
    - mariadb-server-5.5
    - mariadb-client-5.5
    - python-mysqldb

- name: Start MariaDB
  service: name=mysql state=started

- name: update mysql root password for all root accounts
  mysql_user: 'name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT'
  with_items:  
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Add default db user
  mysql_user: 'name={{ mysql_username }} password={{ mysql_password }} priv=*.*:ALL state=present'
