---
- hosts: all
  sudo: true

  vars_files:
    - ../ansible_config.yml

  vars: 
    # global variable default fallbacks defined here, will be overridden by the vars_file
    synced_folder: /vagrant_synced 

  pre_tasks:

    - name: write the motd
      template: src=templates/motd.j2 dest=/etc/motd

    - name: Update apt cache
      apt: update_cache=yes

    - name: install python-software-properties (required for Ansible)
      apt: pkg=python-software-properties state=installed

    - name: Install some basic tools
      apt: pkg={{ item }} state=installed
      with_items:
        - make
        - vim
        - curl

    - name: Set up linked folder {{ synced_folder }}
      file: path={{ synced_folder }} state=directory mode=0777 force=yes

    - name: Link standard share to {{ synced_folder }}
      file: dest={{ synced_folder }}/{{ ansible_hostname }} src=/vagrant state=link mode=0777 force=yes

  roles:
    - sshfs
    - apache
    - php
    - node
    - mariadb
    - avahi

  tasks:

