---
- hosts: all
  sudo: true

  vars_files:
    - ../ansible_config.yml

  pre_tasks:
  
    - debug: "msg=\"{{ ansible_env }}  and this... {{ ansible_env['PWD'] }}\""

    - name: write the motd
      template: src=templates/motd.j2 dest=/etc/motd

    - name: Update apt cache
      apt: update_cache=yes

    - name: install python-software-properties (required for Ansible)
      apt: pkg=python-software-properties state=installed

    - name: Install some basic tools
      apt: pkg={{ item }} state=installed
      with_items:
        - make
        - vim
        - curl

  roles:
    - apache
    - php
    - mariadb
    - avahi

  tasks:

