---
- hosts: all
  sudo: true

  vars_files:
    - ../ansible_config.yml

  pre_tasks:

    - name: write the motd
      template: src=templates/motd.j2 dest=/etc/motd

    - name: Update apt cache
      apt: update_cache=yes

    - name: install python-software-properties (required for Ansible)
      apt: pkg=python-software-properties state=installed

    - name: Install some basic tools
      apt: pkg={{ item }} state=installed
      with_items:
        - make
        - vim
        - curl

  roles:
    - apache
    - php
    # - node
    # node was supposed to be for Grunt LiveReload, but NFS is too slow noticing 
    # changes to shared folders. Install it locally and run grunt watch from there
    - mariadb
    - avahi

  tasks:

