---
- hosts: all
  sudo: true

  vars_files:
    - ../ansible_config.yml

  vars: 
    # global variable default fallbacks defined here, will be overridden by the vars_file
    synced_folder: /vagrant_synced 

  pre_tasks:

    - name: write the motd
      template: src=templates/motd.j2 dest=/etc/motd

    - name: Fix grub timeout
      lineinfile:
        dest=/etc/grub.d/00_header
        regexp="^\s+set timeout=(-1|10)"
        line="  set timeout=10"

    - name: Update grub with new recordfail timeout
      command: update-grub

    - name: Update apt cache
      apt: update_cache=yes

    - name: install python-software-properties (required for Ansible)
      apt: pkg=python-software-properties state=installed

    - name: Set up linked folder {{ synced_folder }}
      file: path={{ synced_folder }} state=directory mode=0777 owner=vagrant group=vagrant

    # - name: Link standard share to {{ synced_folder }}
    #   file: dest={{ synced_folder }}/{{ ansible_hostname }} src=/vagrant state=link mode=0777

    # - name: Check if the NFS mount exists
    #   stat: path=/mnt/nfs/{{ ansible_hostname }}
    #   register: nfs_mount

    # - name: Link NFS mount to {{ synced_folder }} (overwrite previous links)
    #   file: dest={{ synced_folder }}/{{ ansible_hostname }} src=/mnt/nfs/{{ ansible_hostname }} state=link mode=0777 owner=vagrant group=vagrant force=yes
    #   when: nfs_mount.stat.exists

  roles:
    # - sshfs
    - apache
    - php
    - node
    - mariadb
    - avahi

  tasks:

