---

- name: install Apache
  apt: name={{ item }} state=installed update_cache=yes
  with_items: 
    - apache2

- name: Make Apache2 not suck
  command: a2enmod {{ item }}
  with_items:
    - rewrite
    - expires
  notify:
    - restart apache
