---

- name: Remove pre-existing generated keys
  file: path={{ item }} state=absent
  with_items: 
    - "{{ ssh_key_file }}"
    - "{{ ssh_key_file }}.pub"

- name: Generate new ssh keys
  command: "ssh-keygen -t rsa -f {{ ssh_key_file }} -q -N ''"

- name: Get contents of new ssh public key
  command: "cat {{ ssh_key_file }}.pub"
  register: ssh_public_key

- name: Insert key into hosts's authorized_keys file
  sudo: no
  local_action: 
    lineinfile
    dest=~/.ssh/authorized_keys
    regexp="vagrant@{{ ansible_hostname }}$"
    line="{{ ssh_public_key.stdout }}"



## TODO: fix this, is not idempotent, recreates the top-half each time
- name: Create ssh_config temp file
  command: mktemp /tmp/ssh_config-XXXX
  register: ssh_temp

- debug: 'msg="this is ssh_temp: {{ ssh_temp.stdout }}"'

- name: Generate vagrant-host SSH config entry
  template: src=config.j2 dest={{ ssh_temp.stdout }}

- name: Append existing global ssh_config
  shell: cat /etc/ssh/ssh_config >> {{ ssh_temp.stdout }}

- name: Replace global ssh_config
  shell: cat {{ ssh_temp.stdout }} > /etc/ssh/ssh_config

## END non-idempotent section ^^^^


- name: Fix ~/.ssh permissions
  file: path=/home/vagrant/.ssh recurse=yes owner=vagrant group=vagrant state=directory

- name: Install sshfs
  apt: pkg={{ item }} state=installed update_cache=no
  with_items:
    - sshfs
    - autofs

# TODO: Is this necessary?
- name: Add vagrant user to fuse group
  user:  name=vagrant groups=fuse append=true

- name: Enable 'user_allow_other' in /etc/fuse.conf
  lineinfile: 
    dest=/etc/fuse.conf
    regexp="#?user_allow_other"
    line=user_allow_other
    mode=0644

- name: Create /mnt/sshfs mountpoint
  file: path=/mnt/sshfs/ state=directory mode=0777

- name: Generate autofs.master
  template: src=auto.master.j2 dest=/etc/auto.master mode=0644
  notify:
    - Restart autofs

- name: Generate autofs.sshfs
  template: src=auto.sshfs.j2 dest=/etc/auto.sshfs mode=0644
  notify:
    - Restart autofs

- name: Add autofs startup to rc.local
  lineinfile: 
    dest=/etc/rc.local
    regexp="service autofs start.*$"
    line="service autofs start"
    insertbefore="^exit"
