---

- name: Set up Bonjour/Zeroconf (avahi-daemon)
  apt: pkg=avahi-daemon state=installed update_cache=yes

- name: Advertise site with Zeroconf
  template: src=httpd.service.j2 dest=/etc/avahi/services/httpd.service mode=0644 
  notify: 
    - restart avahi