---

- name: Install Yeoman (includes Grunt, Bower and Yo)
  npm: name=yo global=yes state=latest

- name: Make sure RubyGems is installed
  apt: pkg=rubygems state=installed update_cache=yes

- name: Install Compass gem (ruby, includes Sass)
  gem: name=compass state=latest user_install=no

- name: Check for package.json file to install from
  stat: path=/vagrant/{{ package_json_file }}
  register: package_json_stat

- name: NPM install from package.json (if exists)
  npm:  path=/vagrant/{{ package_json_file | dirname }} state=latest
  when: package_json_stat.stat.exists

- name: Check for Gruntfile.js file
  stat: path=/mnt/sshfs/{{ ansible_hostname }}/{{ gruntfile }}
  register: gruntfile_stat

- name: Kill any pre-existing Grunt processes
  command: killall grunt
  ignore_errors: yes

- name: Run grunt watch in the background (if Gruntfile.js exists)
  shell: grunt watch > /var/log/grunt.log chdir=/mnt/sshfs/{{ ansible_hostname }}
  async: 3141592653  #99+ years, will be switchd to 0 when https://github.com/ansible/ansible/pull/4807 is merged
  poll: 0
  when: gruntfile_stat.stat.exists
